### ISSUE TITLE
Errors when creating Github issues

### ISSUE THREAD

**Issue by marcos-lg** [gbif/collections-sync#413]
Sometimes we get errors like this:

ERROR org.gbif.collections.sync.clients.http.SyncCall - Service responded with an error Response{protocol=http/1.1, code=500, message=Internal Server Error, url=[https://api.github.com/repos/gbif/collections-sync/issues/84}](https://api.github.com/repos/gbif/collections-sync/issues/84%7D)

There are more here: https://builds.gbif.org/job/run-collections-sync/501/console

**Comment by ahakanzn** [comment]
fixed and deployed to prod
